### ISSUE TITLE
Pattern is no longer compatible with kivy 1.9.?

### ISSUE THREAD

**Issue by jtownley** [tito/kivy-gettext-example#2]
Seemly as of 1.9 the implict bind in kivy/lang.py is no longer called. My understanding is that this was replaced by kivy.lang.Observable which cannot be extended in conjunction with str due to a "multiple bases have instance lay-out conflict"

This little example is one of the best I have seen for i18n in kivy and delivers a lot of value to anyone doing the i18n thing.

**Comment by ecdsa** [comment]
I am stuck here too... would be nice to hear of a solution

**Comment by akshayaurora** [comment]
change lang.kv to include the following

```
#:import _ __main__._
#:import partial functools.partial

<Label>
    bound: False
    on_text:
        def updtxt(t, l): self.text = l(t)
        if not self.bound: self.bound = True; _.bind(_=partial(updtxt, args[1], _))
```

This should fix the example to work with 1.9.1

**Comment by ecdsa** [comment]
thanks

**Comment by tito** [comment]
The latest example have a new approach that is compatible with kivy 1.9 and fbind(). Please test and report any issue :)
